#!/usr/bin/env bash
# This script will Configure the Nginx server so that 
# /redirect_me is redirecting to another page.

# Install nginx
sudo apt update -y
sudo apt install nginx -y

# Configure the output
echo "Hello World!" | sudo tee /var/www/html/index.html

sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me kevinkoech.tech permanent;' /etc/nginx/sites-available/default

# Strart nginx
sudo service nginx restart
