#!/usr/bin/env bash
# This script pings an IP address passed as an argument

# Check if argument is passed
if [ $# -eq 0 ]; then
  echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
  exit 1
fi

# Perform 5 pings
# $1 refers to first argument
ping -c 5 "$1"
