#!/usr/bin/env bash
# Creates the file /var/run/myscript.pid containing its PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

# creating and writing to the file
sudo touch /var/run/myscript.pid

# using the tee command with sudo to write to the file with elevated privileges
# The ">/dev/null" part is used to discard the output from tee, preventing it from being displayed in the terminal.
echo $$ | sudo tee /var/run/myscript.pid >/dev/null

# using trap to catch signals
trap "echo I hate the kill command; sudo rm -rf /var/run/myscript.pid; exit" SIGTERM
trap "echo Y U no love me?!; exit" SIGINT
trap "sudo rm -rf /var/run/myscript.pid; exit" SIGQUIT

while true
do
  echo "To infinity and beyond"
  sleep 2
done
