#!/usr/bin/env bash
# This script displays numbers from 1 to 20 and:
# displays 4 and then bad luck from China for the 4th loop iteration
# displays 9 and then bad luck from Japan for the 9th loop iteration
# displays 17 and then bad luck from Italy for the 17th loop iteration

# Creating and initializing count
count=1

# While loop
while [ $count -lt 21 ]
do
  echo "$count"
  ((count++))
  case $count in
    4)
      echo "$count bad luck from China"
      ;;
    9)
      echo "$count" bad luck from Japan
      ;;
    17)
      echo "$count bad luck from Italy"
  esac
done
