#!/usr/bin/env bash
# This script installs ufw in the server and sets a firewall
# that blocks all incoming traffic except from
# port 22, 443 and 80

# Updating packages and installing ufw
sudo apt update -y
sudo apt install ufw -y

# Enable ufw
sudo ufw enable

# Allow incoming traffic for SSH (port 22), HTTPS (port 443), and HTTP (port 80)
sudo ufw allow ssh  # just because 
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp

# Double checking if incoming traffic is blocked
sudo ufw default deny incoming

# Check status
sudo ufw status

# Starting ufw at boot
sudo systemctl enable ufw
