#!/usr/bin/env bash
# This script configures an ubuntu server with below requirements
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8.

# Creating a copy
cp /etc/hosts ~/hosts.new

# Writing the mapping for localhost
echo -e "127.0.0.2\tlocalhost" >~/hosts.new

# Appending the mapping for facebook
echo -e "8.8.8.8\tfacebook" >>~/hosts.new

# Overwriting the original /etc/hosts file
cp -f ~/hosts.new /etc/hosts
