#!/usr/bin/env bash
# This script creates RSA key pair whose 
# Name of the created private key must be school
# Number of bits in the created key to be created 4096
# The created key must be protected by the passphrase betty

ssh-keygen -t rsa -b 4096 -f school -N betty
